spring:
  application:
    name: timefit-back
  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.example.timefit: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

timefit:
  storage:
    type: local
    path: ./uploads